[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt",
    "src/**",
    "railway.toml",
    "Dockerfile",
]

[service]
start = "gunicorn saas.wsgi:application --bind 0.0.0.0:8080"